// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/materials": {
            "get": {
                "description": "Retrieves cardboard flute profiles and load limits directly from SQLite.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "List Cardboard Flute Profiles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.MaterialResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pack": {
            "post": {
                "description": "Accepts chat messages, retrieval parameters, and LLM hyperparameters to return optimized 3D coordinate placements.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spatial Engine"
                ],
                "summary": "Run 3D Bin Packing Optimization Agent",
                "parameters": [
                    {
                        "description": "Packing agent request payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PackRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BinPackingResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "LLM or DB error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/recommend": {
            "post": {
                "description": "Accepts product specs, checks Postgres for clearance rules, and queries Gemini @ Temp 0.0",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packaging"
                ],
                "summary": "Calculate optimal packaging box and dieline",
                "parameters": [
                    {
                        "description": "Product Specification Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ProductInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recommended FEFCO box and SVG layout",
                        "schema": {
                            "$ref": "#/definitions/main.PackagingRecommendation"
                        }
                    },
                    "400": {
                        "description": "Invalid input error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal processing error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/styles": {
            "get": {
                "description": "Fetches available FEFCO standard container specifications directly from SQLite.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "List FEFCO Structural Box Styles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.BoxStyleResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BinPackingResponse": {
            "type": "object",
            "properties": {
                "ai_recommendation": {
                    "type": "string"
                },
                "bin_dimensions": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        600,
                        400,
                        400
                    ]
                },
                "execution_time": {
                    "type": "string",
                    "example": "12.4ms"
                },
                "fill_percentage": {
                    "type": "number",
                    "example": 84.5
                },
                "placements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PackedPlacement"
                    }
                }
            }
        },
        "handlers.BoxStyleResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "Shipping"
                },
                "code": {
                    "type": "string",
                    "example": "FEFCO 0201"
                },
                "description": {
                    "type": "string",
                    "example": "Standard meeting flap box"
                },
                "name": {
                    "type": "string",
                    "example": "Regular Slotted Container"
                }
            }
        },
        "handlers.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Pack 2 boxes of 200x150x100mm into a standard container."
                },
                "role": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "handlers.MaterialResponse": {
            "type": "object",
            "properties": {
                "max_weight_kg": {
                    "type": "number",
                    "example": 10
                },
                "profile": {
                    "type": "string",
                    "example": "E-Flute"
                },
                "thickness_mm": {
                    "type": "number",
                    "example": 1.5
                }
            }
        },
        "handlers.PackRequestPayload": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ChatMessage"
                    }
                },
                "retrieval_k": {
                    "type": "integer",
                    "example": 3
                },
                "temperature": {
                    "type": "number",
                    "example": 0.7
                },
                "top_k": {
                    "type": "integer",
                    "example": 40
                }
            }
        },
        "handlers.PackedPlacement": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#2563eb"
                },
                "dim": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        200,
                        150,
                        100
                    ]
                },
                "item_id": {
                    "type": "string",
                    "example": "item-101"
                },
                "pos": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        0,
                        0,
                        0
                    ]
                }
            }
        },
        "main.PackagingRecommendation": {
            "type": "object",
            "properties": {
                "box_style": {
                    "type": "string",
                    "example": "FEFCO 0201"
                },
                "dieline_svg": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "main.ProductInput": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "number",
                    "example": 150
                },
                "length": {
                    "type": "number",
                    "example": 300
                },
                "weight": {
                    "type": "number",
                    "example": 2.5
                },
                "width": {
                    "type": "number",
                    "example": 200
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
